# Generated by Django 4.0.4 on 2022-06-11 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='background',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='password',
            field=models.TextField(blank=True, null=True),
        ),
    ]
