# Generated by Django 4.0.4 on 2022-06-19 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_message_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='type',
            new_name='messageType',
        ),
    ]
