# Generated by Django 4.0.4 on 2022-06-26 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_rename_type_message_messagetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(default='1.PNG', upload_to='static/group/profilePicture'),
            preserve_default=False,
        ),
    ]
