# Generated by Django 4.0.4 on 2022-06-26 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0009_user_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profileImage',
            field=models.ImageField(upload_to='static/group/profilePicture', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
